6.Python: 주문수분석(후기)
#오류 1 
join_data.groupby('payment_month').sum()['price']

payment_month 데이터타입이 object 인데도 계속 
TypeError: datetime64 type does not support sum operations
라는 오류가 발생
챗지피티한테 물어봤지만 이상한 소리만 함
구글링 함
#구글링
#https://stackoverflow.com/questions/77062953/exclude-datetime-from-groupby-sum
join_data.groupby(['payment_month'])[['price']].sum()
price 칼럼을 sum 앞으로 위치를 바꾸는 것만으로 문제 해결
이유는 모름 
책보고 그대로 했는데 난 왜 안되는 것인가

#오류 2 json 파일로 저장됨
jupyter notebook이나 jupyter lab 쓰면서 한번도 이런적 없어서 당황... 첨엔 저게 json 파일인지도 몰랐음
어째저쨰 구글링 하다가 jupyter lab 내부 터미널에서 convert 하는 명령어를 설치하고 ipynb 로 확장자를 바꾸면 된다고 함
똑같이 따라했는데 난 왜 안됨
다시 구글링 함... 자료가 몇개 없고 있는거 다 따라해도 안고쳐짐
챗지피티 또 이상한 소리만 함
그래서 확장자를 바꾸라길래 그냥 내 컴퓨터 드라이브에 있는 저장된 json 파일에 이름바꾸기를 눌러서 .ipynb 만 끝에 추가함
?됨

오늘의 후기 : 오류가 왜 났는지 이게 무슨 오류인지 고치는 방법 등은 찾는데 한세월이 걸리는데 막상 오류를 고치는 방법은 너무 쉽고 간단하다...

코드와 csv 파일 출처는 <파이썬 데이터 분석 실무 테크닉 100>